 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/payment_details", type: :request do
  
  # PaymentDetail. As you add validations to PaymentDetail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PaymentDetail.create! valid_attributes
      get payment_details_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      payment_detail = PaymentDetail.create! valid_attributes
      get payment_detail_url(payment_detail)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_payment_detail_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      payment_detail = PaymentDetail.create! valid_attributes
      get edit_payment_detail_url(payment_detail)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PaymentDetail" do
        expect {
          post payment_details_url, params: { payment_detail: valid_attributes }
        }.to change(PaymentDetail, :count).by(1)
      end

      it "redirects to the created payment_detail" do
        post payment_details_url, params: { payment_detail: valid_attributes }
        expect(response).to redirect_to(payment_detail_url(PaymentDetail.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PaymentDetail" do
        expect {
          post payment_details_url, params: { payment_detail: invalid_attributes }
        }.to change(PaymentDetail, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post payment_details_url, params: { payment_detail: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested payment_detail" do
        payment_detail = PaymentDetail.create! valid_attributes
        patch payment_detail_url(payment_detail), params: { payment_detail: new_attributes }
        payment_detail.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the payment_detail" do
        payment_detail = PaymentDetail.create! valid_attributes
        patch payment_detail_url(payment_detail), params: { payment_detail: new_attributes }
        payment_detail.reload
        expect(response).to redirect_to(payment_detail_url(payment_detail))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        payment_detail = PaymentDetail.create! valid_attributes
        patch payment_detail_url(payment_detail), params: { payment_detail: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested payment_detail" do
      payment_detail = PaymentDetail.create! valid_attributes
      expect {
        delete payment_detail_url(payment_detail)
      }.to change(PaymentDetail, :count).by(-1)
    end

    it "redirects to the payment_details list" do
      payment_detail = PaymentDetail.create! valid_attributes
      delete payment_detail_url(payment_detail)
      expect(response).to redirect_to(payment_details_url)
    end
  end
end
