 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tenant_details", type: :request do
  
  # TenantDetail. As you add validations to TenantDetail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TenantDetail.create! valid_attributes
      get tenant_details_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tenant_detail = TenantDetail.create! valid_attributes
      get tenant_detail_url(tenant_detail)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tenant_detail_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      tenant_detail = TenantDetail.create! valid_attributes
      get edit_tenant_detail_url(tenant_detail)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TenantDetail" do
        expect {
          post tenant_details_url, params: { tenant_detail: valid_attributes }
        }.to change(TenantDetail, :count).by(1)
      end

      it "redirects to the created tenant_detail" do
        post tenant_details_url, params: { tenant_detail: valid_attributes }
        expect(response).to redirect_to(tenant_detail_url(TenantDetail.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TenantDetail" do
        expect {
          post tenant_details_url, params: { tenant_detail: invalid_attributes }
        }.to change(TenantDetail, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tenant_details_url, params: { tenant_detail: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tenant_detail" do
        tenant_detail = TenantDetail.create! valid_attributes
        patch tenant_detail_url(tenant_detail), params: { tenant_detail: new_attributes }
        tenant_detail.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tenant_detail" do
        tenant_detail = TenantDetail.create! valid_attributes
        patch tenant_detail_url(tenant_detail), params: { tenant_detail: new_attributes }
        tenant_detail.reload
        expect(response).to redirect_to(tenant_detail_url(tenant_detail))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tenant_detail = TenantDetail.create! valid_attributes
        patch tenant_detail_url(tenant_detail), params: { tenant_detail: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tenant_detail" do
      tenant_detail = TenantDetail.create! valid_attributes
      expect {
        delete tenant_detail_url(tenant_detail)
      }.to change(TenantDetail, :count).by(-1)
    end

    it "redirects to the tenant_details list" do
      tenant_detail = TenantDetail.create! valid_attributes
      delete tenant_detail_url(tenant_detail)
      expect(response).to redirect_to(tenant_details_url)
    end
  end
end
