 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/userdashboards", type: :request do
  
  # Userdashboard. As you add validations to Userdashboard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Userdashboard.create! valid_attributes
      get userdashboards_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      userdashboard = Userdashboard.create! valid_attributes
      get userdashboard_url(userdashboard)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_userdashboard_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      userdashboard = Userdashboard.create! valid_attributes
      get edit_userdashboard_url(userdashboard)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Userdashboard" do
        expect {
          post userdashboards_url, params: { userdashboard: valid_attributes }
        }.to change(Userdashboard, :count).by(1)
      end

      it "redirects to the created userdashboard" do
        post userdashboards_url, params: { userdashboard: valid_attributes }
        expect(response).to redirect_to(userdashboard_url(Userdashboard.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Userdashboard" do
        expect {
          post userdashboards_url, params: { userdashboard: invalid_attributes }
        }.to change(Userdashboard, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post userdashboards_url, params: { userdashboard: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested userdashboard" do
        userdashboard = Userdashboard.create! valid_attributes
        patch userdashboard_url(userdashboard), params: { userdashboard: new_attributes }
        userdashboard.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the userdashboard" do
        userdashboard = Userdashboard.create! valid_attributes
        patch userdashboard_url(userdashboard), params: { userdashboard: new_attributes }
        userdashboard.reload
        expect(response).to redirect_to(userdashboard_url(userdashboard))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        userdashboard = Userdashboard.create! valid_attributes
        patch userdashboard_url(userdashboard), params: { userdashboard: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested userdashboard" do
      userdashboard = Userdashboard.create! valid_attributes
      expect {
        delete userdashboard_url(userdashboard)
      }.to change(Userdashboard, :count).by(-1)
    end

    it "redirects to the userdashboards list" do
      userdashboard = Userdashboard.create! valid_attributes
      delete userdashboard_url(userdashboard)
      expect(response).to redirect_to(userdashboards_url)
    end
  end
end
